"""Added units table

Revision ID: 680d95d49003
Revises: b7e5cb33e483
Create Date: 2026-08-20 11:15:56.402271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '680d95d49003'
down_revision = 'b7e5cb33e483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unitID', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('unitCode', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('unitName', sa.String(length=100), nullable=False))
        batch_op.drop_column('unit_code')
        batch_op.drop_column('unit_id')
        batch_op.drop_column('unit_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('unit_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('unit_code', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('unitName')
        batch_op.drop_column('unitCode')
        batch_op.drop_column('unitID')

    # ### end Alembic commands ###
