"""Added units table

Revision ID: 70ed96e5dbc7
Revises: 680d95d49003
Create Date: 2026-08-20 11:56:31.916347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ed96e5dbc7'
down_revision = '680d95d49003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('unitID', sa.Integer(), nullable=False),
    sa.Column('unitCode', sa.String(length=20), nullable=False),
    sa.Column('unitName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('unitID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    # ### end Alembic commands ###
