"""Added student units relationship table

Revision ID: 91fcd477d6f8
Revises: 70ed96e5dbc7
Create Date: 2026-08-20 12:46:58.191255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91fcd477d6f8'
down_revision = '70ed96e5dbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_units',
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('unitID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['studentID'], ['students_x.studentID'], ),
    sa.ForeignKeyConstraint(['unitID'], ['units.unitID'], ),
    sa.PrimaryKeyConstraint('studentID', 'unitID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_units')
    # ### end Alembic commands ###
