"""Add email column

Revision ID: b7e5cb33e483
Revises: 4475d483ebb1
Create Date: 2026-07-01 10:39:52.131066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e5cb33e483'
down_revision = '4475d483ebb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_x', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_x', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
